##################################
#定义项目使用到的基础库头文件路径#
#定义项目使用到的基础静态路路径  #
##################################

#基础库路径
PLIB_DIR                = ${PROJECT_BASE_PATH}/submodules/plib/

SPP_INC                 = -I${PLIB_DIR}/spp/include
BASELIB_INC             = -I${PLIB_DIR}/baselib/include
BASELIB_LIB             = -L${PLIB_DIR}/baselib/lib -lhy_base

PROTO_INC               = -I${PROJECT_BASE_PATH}/proto_cc
PROTO_LIB                = -L${PROJECT_BASE_PATH}/proto_cc -lroompb

#common 公共代码
COMMON_DIR              = ${PROJECT_BASE_PATH}/room_common
COMMON_LIB_FILE         = ${PROJECT_BASE_PATH}/lib/liblivecommon.a
COMMON_INC              = -I${COMMON_DIR}/include \
						  -I${COMMON_DIR}/include/client \
						  -I${COMMON_DIR}/include/constant \
						  -I${COMMON_DIR}/include/dao \
						  -I${COMMON_DIR}/include/service \
						  -I${COMMON_DIR}/include/util \
						  -I${COMMON_DIR}/src/antispam \
                                                  -I${COMMON_DIR}/include/zk
COMMON_LIB              = -L${COMMON_LIB_FILE}

#outerlib 基础库
PROTOBUF_INC              = -I${PLIB_DIR}/outerlib/protobuf-2.6.1/include
PROTOBUF_LIB              = -L${PLIB_DIR}/outerlib/protobuf-2.6.1/lib -lprotobuf

THRIFT_INC              = -I${PLIB_DIR}/outerlib/thrift-0.8.0/include
THRIFT_LIB              = -L${PLIB_DIR}/outerlib/thrift-0.8.0/lib -lthriftnb -lthrift

THRIFT_0.5_INC          = -I${PLIB_DIR}/outerlib/thrift-0.5.0/include
THRIFT_0.5_LIB          = -L${PLIB_DIR}/outerlib/thrift-0.5.0/lib -lthriftnb -lthrift

LIBEVENT_INC            = -I${PLIB_DIR}/outerlib/libevent-2.0.22/include
LIBEVENT_LIB            = -L${PLIB_DIR}/outerlib/libevent-2.0.22/lib -levent -lrt

ZLIB_INC                = -I${PLIB_DIR}/outerlib/zlib-1.2.8/include
ZLIB_LIB                = -L${PLIB_DIR}/outerlib/zlib-1.2.8/lib -lz

HIREDIS_INC             = -I${PLIB_DIR}/outerlib/hiredis-0.12.1/include
HIREDIS_LIB             = -L${PLIB_DIR}/outerlib/hiredis-0.12.1/lib/ -lhiredis

JSONC_INC               = -I${PLIB_DIR}/outerlib/json-c-1.6/include
JSONC_LIB               = -L${PLIB_DIR}/outerlib/json-c-1.6/lib/ -ljson-c

JSONCPP_INC               = -I${PLIB_DIR}/outerlib/jsoncpp-1.6.2/include
JSONCPP_LIB               = -L${PLIB_DIR}/outerlib/jsoncpp-1.6.2/lib/ -ljsoncpp

ZOOKEEPER_INC           = -I${PLIB_DIR}/outerlib/zkclient-3.4.6/include
ZOOKEEPER_LIB           = -L${PLIB_DIR}/outerlib/zkclient-3.4.6/lib -lzookeeper_mt

OPENSSL_INC             = -I${PLIB_DIR}/outerlib/openssl-1.0.2a/include
OPENSSL_LIB             = -L${PLIB_DIR}/outerlib/openssl-1.0.2a/lib -lssl -lcrypto

BOOST_INC               = -I${PLIB_DIR}/outerlib/boost-1.14.0/include
BOOST_LIB               = -L${PLIB_DIR}/outerlib/boost-1.14.0/lib -lboost_thread

CURL_INC                = -I${PLIB_DIR}/outerlib/curl-7.45.0/include
CURL_LIB                = -L${PLIB_DIR}/outerlib/curl-7.45.0/lib -lcurl


#webapp_syncframe_v2 基础库
SYNC_FRAME_V2_INC       = -I${PLIB_DIR}/webapp_syncframe_v2/include/
SYNC_FRAME_V2_LIB       = -L${PLIB_DIR}/webapp_syncframe_v2/lib -lwebappsyncframe

#applib 基础库
ZHIBOUTIL_INC           = -I${PLIB_DIR}/applib/zhibo_util/include
ZHIBOUTIL_LIB           = -L${PLIB_DIR}/applib/zhibo_util/lib -lzhibo_util

MILINK_INC              = -I${PLIB_DIR}/applib/milink_api/include
MILINK_LIB              = -L${PLIB_DIR}/applib/milink_api/lib -lhy_milink_api

IRIS_API_INC           = -I${PLIB_DIR}/applib/Iris_api_v3/include
IRIS_API_LIB           = -L${PLIB_DIR}/applib/Iris_api_v3/lib -liris_api

MLIST_API_INC           = -I${PLIB_DIR}/applib/mlist_api/include
MLIST_API_LIB           = -L${PLIB_DIR}/applib/mlist_api/lib -lmlist_api

MLIST_API_PROTO_INC     = -I${PLIB_DIR}/applib/mlist_api/proto
      
BITMAP_API_INC          = -I${PLIB_DIR}/applib/bitmap_api/include
BITMAP_API_LIB          = -L${PLIB_DIR}/applib/bitmap_api/lib -lbitmap_api

HY_MSTORE_API_INC       = -I${PLIB_DIR}/applib/hy_mstore_api_v2/include
HY_MSTORE_API_LIB       = -L${PLIB_DIR}/applib/hy_mstore_api_v2/lib -lhy_mstore_api

HY_SCRIBE_API_INC       = -I${PLIB_DIR}/applib/hy_scribe_api/include
HY_SCRIBE_API_LIB       = -L${PLIB_DIR}/applib/hy_scribe_api/lib -lhy_scribe_client

ZOOKEEPER_AGENT_INC     = -I${PLIB_DIR}/applib/zk_agent_client_api/include
ZOOKEEPER_AGENT_LIB     = -L${PLIB_DIR}/applib/zk_agent_client_api/lib -lzk_agent_client

MLB_INC                 = -I${PLIB_DIR}/mlb/include
MLB_LIB                 = -L${PLIB_DIR}/mlb/lib -lqos_client

MISF_INC                = -I$(PLIB_DIR)/misf/include
BASE                    = $(MISF_INC)/base
OLD                     = $(MISF_INC)/old
COMMON                  = $(MISF_INC)/common
CCD                     = $(MISF_INC)/ccd
MCD                     = $(MISF_INC)/mcd
DCC                     = $(MISF_INC)/dcc
MCP_INC                 = $(BASE) $(OLD) $(COMMON) $(CCD) $(MCD) $(DCC)
MCP_LIB                 = -L$(PLIB_DIR)/misf/lib -lmisf

PASSPORT_INC            = -I$(PLIB_DIR)/passport_sdk/src
PASSPORT_LIB            = -L$(PLIB_DIR)/passport_sdk/src -lxiaomi-ppsdk

SERVICE_TOKEN_INC       = -I$(PLIB_DIR)/servicetoken-api/include
SERVICE_TOKEN_LIB       = -L$(PLIB_DIR)/servicetoken-api/lib -lservicetoken_api

B2TOKEN_INC             = -I$(PLIB_DIR)/b2token/include
B2TOKEN_LIB             = -L$(PLIB_DIR)/b2token/lib -lb2token

XTRACE_INC              = -I${PLIB_DIR}/xtrace-client/include
XTRACE_LIB              = -L${PLIB_DIR}/xtrace-client/lib -lxtrace_client

RSA_INC                 = -I$(PLIB_DIR)/security/rsa-utils/include
RSA_LIB                 = -L$(PLIB_DIR)/security/rsa-utils/lib -lrsa-util
